# This is the overall config for a circuit-level test group
["Configs"]
units = ["target", "source"]
debug-modes = ["DEBUG", "INFO", "WARNING", "EXCEPT"]
test-modes = ["DEBUG"]                               # Can be "<MODE>", ["<MODE1>", <"MODE2">, ...], "All"
enabled = true
timeout = 10
use-ai = false
diagnostics = true
detect-bad-behavior = true
save-resume = true
repeat = 0                                           # can be any between 0 - 10
gen-metrics = true
save-metrics = true
save-scores = true
